// Generated by https://quicktype.io

export interface Transfer {
    element_in:       number;
    element_in_cost:  number;
    element_out:      number;
    element_out_cost: number;
    entry:            number;
    event:            number;
    time:             string;
}

type UserTransfer = {
    element_in:  string | undefined;
    element_in_cost: number | undefined;
    element_out:  string | undefined;
    element_out_cost: number| undefined;
    entry: number | undefined;
    event: number | undefined;
    time: string | undefined;
    element_in_web_name:  string | undefined;
    element_out_web_name:  string | undefined;
    element_in_point: number | undefined;
    element_out_point: number | undefined;
    pointDifference: number | undefined;
    element_in_id: number | undefined;
    element_out_id: number | undefined ;
    element_in_photo: string | undefined ;
    element_out_photo: string | undefined;
};

