// Generated by https://quicktype.io

export interface UserGw {
    active_chip:    null;
    automatic_subs: AutomaticSub[];
    entry_history:  { [key: string]: number };
    picks:          Pick[];
    entry:          number | string | undefined;
    userId:         number;
}

export interface AutomaticSub {
    entry:          number;
    element_in:     number;
    element_out:    number;
    event:          number;
    autoSubPoints:  number;
}

export interface Pick {
    element:         number;
    position:        number;
    multiplier:      number;
    is_captain:      boolean;
    is_vice_captain: boolean;
}

// set userDatabase type
export interface UserDatabase  {
    user_id: number;
    name: string;
    favourite_team: string;
    player_first_name: string;
    player_last_name: string;
    player_region_id: number;
    player_region_name: string;
    player_region_iso_code_short: string;
    player_region_iso_code_long: string;
  };
